replicaCount: 2

image:
  repository: nginx
  tag: "1.23.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

proxy:
  upstreamUrl: "http://stage-upstream.com"
  upstreamPort: 8081

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
