replicaCount: 1

image:
  repository: nginx
  tag: "1.23.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

proxy:
  upstreamUrl: "http://example-upstream.com"
  upstreamPort: 8080
