replicaCount: 1

image:
  repository: nginx
  tag: "1.23.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

proxy:
  upstreamUrl: "http://dev-upstream.com"  # Retained the first upstream URL as it seems correct
  upstreamPort: 8080

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"
