replicaCount: 2

image:
  repository: nginx
  tag: "1.23.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

proxy:
  # Ensure the correct upstream URL and port are specified here.
  upstreamUrl: "http://example-upstream.com"
  upstreamPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
